// E36

// EcmaScript 6 or EcmaScript 2015 or ES 2015 OR ES6

// ECMA
// Europran Computer Manufactor Association 
// Code Name for ES6 is ECMA-262

// 1 The original Javascript - ES $2, ES 1997-1999)
// 2. The First Marin revision ESS
// 3. The Second Revision ES6 (2015) ==> Its the biggest update of JS till yet
// 4. Yearly Additions ==> (2016, 2017, 2018, 2019, 2020, 2023) 
// ES 2016, ES2017, ES2018, ES2019...ES2022

// ES 2023
